### ISSUE TITLE
Ingresar usuario(HU-02)(Iteracion-1)

### ISSUE THREAD

**Issue by EmilianoBlazco** [guille1093/SpringWebApp-POO2#3]
### Descripcion Historia de Usuario

**Como** Inquilino/Propietario/Administrador
**Quiero** poder ingresar mi nombre de usuario y contraseña
**Para** poder hacer uso de las funcionalidades del sistema e ingresar a las caracteristicas relacionadas a mi cuenta

**Criterios de aceptacion**

- [x] El nombre de usuario debe existir dentro de la base de datos #13 
- [x] Cuando el ingreso del usuario y contraseña son correctos, entonces el sistema permitirá el ingreso #13 
- [x] Si el usuario ingresa una contraseña incorrecta, el sistema mostrara la opcion de restablecer contraseña #13 

Tareas relacionadas

- [x] Creación de wireframe #8 
**Creación del formulario donde contendrán los siguientes elementos** 
- Posicionamiento de campo de texto para completar “Usuario” 
- Posicionamiento de campo de texto para completar “Contraseña”
- Boton de accion de “Iniciar Sesión” para enviar el formulario
- [x] Descripción del Uso del wireframe (Caso de Uso real) #9 
- [x] Creación del modelo de datos(Entidad/es de Base de datos) #10 
- [x] Establecer funcion de envio de formulario #11 
- [x] Validación de campos con sus respectivas alertas #12
