### ISSUE TITLE
Dar de baja una propiedad(HU-01)

### ISSUE THREAD

**Issue by EmilianoBlazco** [guille1093/SpringWebApp-POO2#33]
### Descripcion Historia de Usuario

**Como** propietario  
**Quiero** Dar de baja una propiedad  
**Para** ocultar una publicación realizada

**Criterios de aceptación:**

- [ ]  El propietario debe ingresar al sistema con su usuario. #37 
- [ ]  La publicación debe existir. #37 
- [ ]  La publicación debe estar activa y no debe estar asociado a un inquilino #37 

**Tareas relacionadas**

Las siguientes tareas comprenderán el desarrollo de la Historia de Usuario:

- [ ] Creación de wireframe #38 
- Incorporación de botón con la funcionalidad de dar de baja y la etiqueta “Dar de baja la publicacion”
- [ ] Descripción del Uso del wireframe (Caso de Uso real) #41 
- [ ] Establecer el cambio de estado en el atributo asociado a la publicación #43
