### ISSUE TITLE
Consultar propiedad(HU-02)

### ISSUE THREAD

**Issue by EmilianoBlazco** [guille1093/SpringWebApp-POO2#34]
### Descripcion Historia de Usuario

**Como** propietario  
**Quiero** Consultar propiedad
**Para** ver los detalles de la misma
 
**Criterios de aceptación:**

- [ ] El propietario debe ingresar al sistema con su usuario. #40 
- [ ] El propietario debe haber registrado al menos 1 propiedad #40 
- [ ] La publicación debe estar activa #40 

**Tareas relacionadas**

Las siguientes tareas comprenderán el desarrollo de la Historia de Usuario:

- [ ] Creación de wireframe #39 

- Etiqueta que contenga el título de la publicación
- Etiqueta que contenga la descripción de la publicación
- Etiqueta que contenga el precio de la publicación
- Sección donde se muestre las comodidades y servicios asociados a la propiedad
- Complemento de mapa para ver la ubicación de la propiedad
- Botón con la Etiqueta “Contactar”
- Botón con la Etiqueta “Agregar a Favoritos”
- Cuadro de Imagen para ver las imágenes asociadas a la publicación
- Botón con la Etiqueta “Dar de Baja”
- Botón con la Etiqueta “Modificar” 

- [ ] Descripción del Uso del wireframe (Caso de Uso real) #42
