### ISSUE TITLE
Modificar Propiedad(HU-04)(Iteracion-1)

### ISSUE THREAD

**Issue by guille1093** [guille1093/SpringWebApp-POO2#4]
### Descripcion Historia de Usuario

Como Propietario
Quiero modificar algun dato relacionado a la propiedad publicada
Para  que, en el caso de que exista un error o cambios a realizar, este se pueda agregar.

Criterios de aceptacion

- [x] Los cambios hechos deben mostrarse en la publicacion una vez confirmados #26 
- [x] La publicacion debe pausarse al realizar cambios #26 

Tareas relacionadas

- [x] Descripción del Uso del wireframe (Caso de Uso real) #27 
- [x] Validación de campos con sus respectivas alertas
