### ISSUE TITLE
Consultar Ubicacion(HU-03)

### ISSUE THREAD

**Issue by EmilianoBlazco** [guille1093/SpringWebApp-POO2#48]
### Descripcion Historia de Usuario

**Como** usuario
**Quiero** Consultar ubicación
**Para** poder encontrar la propiedad de manera más eficiente

**Criterios de aceptación:**

- [x] Debe mostrarse la ubicación asociada en el mapa adjunto a la publicación #51 
- [x] La ubicación especificada debe coincidir con la exhibida en el mapa #51

**Tareas relacionadas**

Las siguientes tareas comprenderán el desarrollo de la Historia de Usuario:

- [x] Creación de wireframe #49 
- Dentro del wireframe usado en la Historia de Usuario consultar una propiedad se incorpora un mapa el cual muestre la ubicación ingresada por el propietario
- [x] Descripción del Uso del wireframe (Caso de Uso real) #50
