### ISSUE TITLE
Dar de baja un usuario (baja lógica)(HU-01)

### ISSUE THREAD

**Issue by EmilianoBlazco** [guille1093/SpringWebApp-POO2#58]
### Descripcion Historia de Usuario

**Como** Usuario
**Quiero** dar de baja un usuario
**Para**  eliminar una cuenta registrada

**Criterios de aceptación:**

- [x] El Usuario debe ingresar al sistema con su usuario. #70 
- [x] El usuario debe completar los campos requeridos correctamente #70 

**Tareas relacionadas**

Las siguientes tareas comprenderán el desarrollo de la Historia de Usuario:

- [x] Creación de wireframe #68 
-  Incorporación de botón con la funcionalidad de dar de baja y la etiqueta “Dar de baja”
- [x] Descripción del Uso del wireframe (Caso de Uso real) #69
