### ISSUE TITLE
Agregar un alquiler a Favoritos (baja lógica)(HU-02)

### ISSUE THREAD

**Issue by EmilianoBlazco** [guille1093/SpringWebApp-POO2#59]
### Descripcion Historia de Usuario

**Como** inquilino
**Quiero** agregar un alquiler a Favoritos
**Para**  poder saber cuales son los alquileres que más me interesaron

**Criterios de aceptación:**

- [x] Se debe poder ver una lista con las publicaciones favoritas de un inquilino #66 

**Tareas relacionadas**

Las siguientes tareas comprenderán el desarrollo de la Historia de Usuario:

- [x] Creación de wireframe #62 
- Agregar un botón con un icono de un corazón para agregar a favoritos
- [x] Descripción del Uso del wireframe (Caso de Uso real) #63
