### ISSUE TITLE
Consultar alquileres Favoritos(HU-01)

### ISSUE THREAD

**Issue by EmilianoBlazco** [guille1093/SpringWebApp-POO2#73]
### Descripcion Historia de Usuario

**Como** inquilino
**Quiero** consultar mis alquileres marcados como favoritos
**Para** poder saber cuales son exactamente mis selecciones

**Criterios de aceptación:**

- [ ] Se deben poder todos los alquileres marcados como favoritos #76 
- [ ] Si se desmarca de favorito un alquiler debe desaparecer de la lista #76 

**Tareas relacionadas**

Las siguientes tareas comprenderán el desarrollo de la Historia de Usuario:

- [ ] Creación de wireframe #74 
> - Agregar boton de de redireccionamiento “Mis favoritos”
>- Mostrar Lista de alquileres que posean el estado de FAVORITO
- [ ] Descripción del Uso del wireframe (Caso de Uso real) #75
